-- SQL Generated from DataInitializer.java

SET NAMES utf8mb4;

-- Store Items
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Céu Limpo', 'Um dia perfeito para aprender', 500, 'BANNER', 'images/banners/banner_ceu.jpg', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Sala de Aula', 'Onde o conhecimento começa', 500, 'BANNER', 'images/banners/banner_quadro_sala.png', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Quiz Clássico', 'Simples e direto ao ponto', 500, 'BANNER', 'images/banners/banner_quiz.png', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Floresta Densa', 'A sabedoria escondida nas árvores', 800, 'BANNER', 'images/banners/banner_floresta.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Castelo Medieval', 'Fortaleza do conhecimento', 800, 'BANNER', 'images/banners/banner_castelo.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Mundo 8-Bits', 'Nostalgia pura em pixeis', 800, 'BANNER', 'images/banners/banner_pixel.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Noite 8-Bits', 'Acalma os teus olhos enquanto jogas', 800, 'BANNER', 'images/banners/banner_pixel_noturno.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Terminal Hacker', 'A invadir a base de dados do Quiz', 800, 'BANNER', 'images/banners/banner_hacker.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Chamas Ardentes', 'Aquece a competição', 1200, 'BANNER', 'images/banners/banner_fogo.jpg', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Oceano Profundo', 'Mergulha num mar de perguntas', 1200, 'BANNER', 'images/banners/banner_agua.jpg', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Gelo Eterno', 'Mente fria e calculista', 1200, 'BANNER', 'images/banners/banner_gelo.jpg', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Luzes de Néon', 'O teu perfil a brilhar na escuridão', 100, 'BANNER', 'images/banners/banner_neon.png', 'Épico', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Apocalipse (Dia)', 'O fim do mundo começou de dia', 1200, 'BANNER', 'images/banners/banner_apocalipse_zumbi_dia.png', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Apocalipse (Tóxico)', 'Tudo o que restou foi a radiação', 1800, 'BANNER', 'images/banners/banner_apocalipse_zumbi_grean.png', 'Lendário', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Apocalipse (Noite)', 'A escuridão esconde os piores medos', 1800, 'BANNER', 'images/banners/banner_apocalipse_zumbi_night.png', 'Lendário', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Galáxia', 'O universo inteiro num só banner', 1800, 'BANNER', 'images/banners/banner_galaxia.jpg', 'Lendário', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('The Best', 'Um título para os verdadeiros campeões', 150, 'BANNER', 'images/banners/banner_the_best.png', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Aura Divina', 'Energia suprema emana de ti', 200, 'BANNER', 'images/banners/banner_aura.png', 'Supremo', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Multiverso', 'Controlas o espaço e o tempo', 3500, 'BANNER', 'images/banners/banner_multiverso.png', 'Supremo', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Banner Supremo', 'O topo da cadeia alimentar do Quiz', 200, 'BANNER', 'images/banners/banner_supremo.png', 'Supremo', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Foi fácil demais!', 'Provoca os adversários', 200, 'TEXT_PHRASE', 'Foi fácil demais!', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Mais sorte na próxima!', 'Provoca os adversários', 200, 'TEXT_PHRASE', 'Mais sorte na próxima!', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Boa jogada! 👏', 'Reconhece a jogada do oponente', 150, 'TEXT_PHRASE', 'Boa jogada! 👏', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Não desistas! 💪', 'Motivação durante a partida', 150, 'TEXT_PHRASE', 'Não desistas! 💪', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Muito fácil! 😎', 'Mostra a tua confiança', 180, 'TEXT_PHRASE', 'Muito fácil! 😎', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Tás pronto? 🔥', 'Aquece o duelo de perguntas', 180, 'TEXT_PHRASE', 'Tás pronto? 🔥', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Boa sorte! 🍀', 'Deseja sorte ao adversário', 150, 'TEXT_PHRASE', 'Boa sorte! 🍀', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Ops... 😂', 'Quando alguém erra feio', 150, 'TEXT_PHRASE', 'Ops... 😂', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: GG EZ', 'Clássico dos gamers', 250, 'TEXT_PHRASE', 'GG EZ', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Essa foi por pouco! 😱', 'Para momentos de quase erro', 220, 'TEXT_PHRASE', 'Essa foi por pouco! 😱', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Tás pronto pro show? 🔥', 'Mostra que vieste para vencer', 240, 'TEXT_PHRASE', 'Tás pronto pro show? 🔥', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Errar faz parte! 😉', 'Consola o adversário com estilo', 220, 'TEXT_PHRASE', 'Errar faz parte! 😉', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Segura essa resposta! ⚡', 'Dispara sabedoria a alta velocidade', 260, 'TEXT_PHRASE', 'Segura essa resposta! ⚡', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: O jogo só acaba no fim! ⏳', 'Reviravoltas até ao último segundo', 250, 'TEXT_PHRASE', 'O jogo só acaba no fim! ⏳', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Sou imparável!', 'Para os campeões', 300, 'TEXT_PHRASE', 'Sou imparável!', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Tenta acompanhar o ritmo! ⚡', 'Para os mais rápidos', 300, 'TEXT_PHRASE', 'Tenta acompanhar o ritmo! ⚡', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: A ler a tua mente! 🔮', 'Prevê cada movimento do adversário', 320, 'TEXT_PHRASE', 'A ler a tua mente! 🔮', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Velocidade da Luz! ⚡', 'Resposta instantânea e certeira', 340, 'TEXT_PHRASE', 'Velocidade da Luz! ⚡', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Acertar é de mestre! 🧠', 'Conhecimento e sabedoria refinada', 360, 'TEXT_PHRASE', 'Acertar é de mestre! 🧠', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Calculado ao milímetro! 📐', 'Estratégia pura e matemática', 350, 'TEXT_PHRASE', 'Calculado ao milímetro! 📐', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: A minha intuição nunca falha! ✨', 'Sexto sentido ativado', 320, 'TEXT_PHRASE', 'A minha intuição nunca falha! ✨', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Sou o Novo Campeão! 👑', 'Exclusivo de Missão ou Loja', 400, 'TEXT_PHRASE', 'Sou o Novo Campeão! 👑', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: O trono é meu! 🏆', 'Para os líderes do ranking', 400, 'TEXT_PHRASE', 'O trono é meu! 🏆', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Respeita o Mestre! 🎩', 'Lição de inteligência em direto', 450, 'TEXT_PHRASE', 'Respeita o Mestre! 🎩', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: 100% de Precisão! 🎯', 'Sem margem para dúvidas', 480, 'TEXT_PHRASE', '100% de Precisão! 🎯', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Génio em Ação! 🧪', 'Ciência e conhecimento no topo', 500, 'TEXT_PHRASE', 'Génio em Ação! 🧪', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Mente de Titânio! 🛡️', 'Inabalável contra qualquer pressão', 450, 'TEXT_PHRASE', 'Mente de Titânio! 🛡️', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Impossível de Derrotar! 🌟', 'Apenas para os invictos', 750, 'TEXT_PHRASE', 'Impossível de Derrotar! 🌟', 'Lendário', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Domínio Absoluto! 👑', 'Controle total sobre o tabuleiro', 900, 'TEXT_PHRASE', 'Domínio Absoluto! 👑', 'Lendário', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Sou o Novo Campeão! 👑', 'Exclusivo Supremo', 50, 'TEXT_PHRASE', 'Sou o Novo Campeão! 👑', 'Supremo', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Lenda Viva do Quiz! 🌌', 'Conhecimento de outra dimensão', 100, 'TEXT_PHRASE', 'Lenda Viva do Quiz! 🌌', 'Supremo', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Eu sou o supremo! ✨', 'Avisa a todos quem manda aqui', 80, 'TEXT_PHRASE', 'Eu sou o supremo! ✨', 'Supremo', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Farmando aura! ✨', 'A acumular respeito na partida', 50, 'TEXT_PHRASE', 'Farmando aura! ✨', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Eu sou cheese! 🧀', 'Sabor inconfundível da vitória', 50, 'TEXT_PHRASE', 'Eu sou cheese! 🧀', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: É só isso? 😂', 'Quando o nível está muito baixo', 40, 'TEXT_PHRASE', 'É só isso? 😂', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Meu pequenote! 🤏', 'Superioridade esmagadora', 60, 'TEXT_PHRASE', 'Meu pequenote! 🤏', 'Supremo', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Você não me vence! 🛡️', 'A barreira impenetrável', 60, 'TEXT_PHRASE', 'Você não me vence! 🛡️', 'Supremo', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Frase: Me solta! 😤', 'Imparável e furioso', 50, 'TEXT_PHRASE', 'Me solta! 😤', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Fogo Lendário 🔥', 'Mostra que estás quente no jogo', 200, 'EMOTE', '🔥', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Óculos de Mestre 😎', 'Estilo e confiança total', 200, 'EMOTE', '😎', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Palmas de Respeito 👏', 'Reconhecimento da boa jogada', 200, 'EMOTE', '👏', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Rindo Demais 😂', 'Gargalhada contagiante', 150, 'EMOTE', '😂', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Chocado 😱', 'Surpresa inacreditável', 150, 'EMOTE', '😱', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Força Total 💪', 'Determinação inabalável', 180, 'EMOTE', '💪', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Trevo da Sorte 🍀', 'Abençoado pelos deuses do Quiz', 180, 'EMOTE', '🍀', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Piscadela 😉', 'Cumplicidade e diversão', 150, 'EMOTE', '😉', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Caveira de Ouro 💀', 'Quando o adversário foi de base', 250, 'EMOTE', '💀', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Frio Calculista 🧊', 'Sangue frio para responder', 220, 'EMOTE', '🧊', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Olhos de Foco 👀', 'De olho em cada jogada', 200, 'EMOTE', '👀', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Troféu de Ouro 🏆', 'O símbolo dos vencedores', 260, 'EMOTE', '🏆', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Silêncio Absoluto 🤫', 'Foco total na pergunta', 220, 'EMOTE', '🤫', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Alvo Certeiro 🎯', 'Na mosca sem hesitar', 250, 'EMOTE', '🎯', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Raio Veloz ⚡', 'Velocidade eletrizante', 300, 'EMOTE', '⚡', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Foguete Cósmico 🚀', 'Rumo ao topo do ranking', 300, 'EMOTE', '🚀', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Mente a Explodir 🤯', 'Perguntas que desafiam a mente', 320, 'EMOTE', '🤯', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Mágico do Quiz 🎩', 'Truques de conhecimento', 350, 'EMOTE', '🎩', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Estrela Brilhante ⭐', 'Brilho de uma estrela', 380, 'EMOTE', '⭐', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Tubarão dos Quizzes 🦈', 'Predador implacável nas partidas', 380, 'EMOTE', '🦈', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Leão Majestoso 🦁', 'O rei da selva do saber', 450, 'EMOTE', '🦁', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Anjo Sábio 😇', 'Respostas iluminadas', 450, 'EMOTE', '😇', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Robô Inteligente 🤖', 'Processador de alto rendimento', 500, 'EMOTE', '🤖', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Sol Radiante ☀️', 'Ilumina a sala com respostas', 450, 'EMOTE', '☀️', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Coroa da Vitória 👑', 'Digno de um verdadeiro mestre', 40, 'EMOTE', '👑', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Bola de Cristal 🔮', 'Previsões infalíveis', 30, 'EMOTE', '🔮', 'Raro', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Cérebro Supremo 🧠', 'Pura inteligência em ação', 45, 'EMOTE', '🧠', 'Raro', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Dragão Místico 🐉', 'Poder ancestral e indomável', 60, 'EMOTE', '🐉', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Fénix Imortal 🦅', 'Ressurge sempre com mais força', 70, 'EMOTE', '🦅', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Galáxia Suprema 🌌', 'Conexão com todo o cosmos', 90, 'EMOTE', '🌌', 'Supremo', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Emoji: Diamante Brilhante 💎', 'Precioso e imbatível', 750, 'EMOTE', '💎', 'Lendário', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('O Angolano', 'Representante da sabedoria de Angola', 100, 'AVATAR', 'images/avatars/avatar_angolano.png', 'Básico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('A Angolana', 'Representante da inteligência de Angola', 100, 'AVATAR', 'images/avatars/avatar_angolana_f.png', 'Básico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('O Moçambicano', 'Representante da sabedoria de Moçambique', 100, 'AVATAR', 'images/avatars/avatar_mocambicano.png', 'Básico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('A Moçambicana', 'Representante da inteligência de Moçambique', 100, 'AVATAR', 'images/avatars/avatar_mocambicana_f.png', 'Básico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('O Brasileiro', 'Representante da sabedoria do Brasil', 100, 'AVATAR', 'images/avatars/avatar_brasileiro.png', 'Básico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('A Brasileira', 'Representante da inteligência do Brasil', 100, 'AVATAR', 'images/avatars/avatar_brasileira_f.png', 'Básico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Raposa Normal', 'Tudo começa com curiosidade', 150, 'AVATAR', 'images/avatars/avatar_raposa_normal.png', 'Básico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Soldado de Honra', 'Pronto para a batalha de perguntas', 200, 'AVATAR', 'images/avatars/avatar_soldado.png', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('O Juiz Supremo', 'A verdade acima de tudo', 250, 'AVATAR', 'images/avatars/avatar_juiz_rigoroso.png', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('O Filósofo', 'Questiona até as perguntas', 250, 'AVATAR', 'images/avatars/avatar_filosofo.png', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Raposa Detetive', 'Investiga os mistérios locais', 350, 'AVATAR', 'images/avatars/avatar_rapousa_detetive.png', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Pixel: O Estudante', 'A saber mais do que parece', 400, 'AVATAR', 'images/avatars/avatar_pixel_estudante.png', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Pixel: A Estudiosa', 'Primeira da turma, sempre', 400, 'AVATAR', 'images/avatars/avatar_pixel_estudante_f.png', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Pixel: O Construtor', 'Cada erro é só mais código', 400, 'AVATAR', 'images/avatars/avatar_pixel_engenheiro.png', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Pixel: O Herói 8-Bit', 'Lenda nos 32 pixels de altura', 450, 'AVATAR', 'images/avatars/avatar_pixel_heroi.png', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Pixel: O Doutor', 'Diagnóstico: muita inteligência', 450, 'AVATAR', 'images/avatars/avatar_pixel_medico.png', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Pixel: O Mestre', 'Sabe a resposta antes da pergunta', 450, 'AVATAR', 'images/avatars/avatar_pixel_professor.png', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Pixel: O Dev', 'Código é o seu superpoder', 80, 'AVATAR', 'images/avatars/avatar_pixel_it.png', 'Incomum', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Pixel: O Vilão', 'O lado sombrio do saber', 80, 'AVATAR', 'images/avatars/avatar_pixel_vilao.png', 'Incomum', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Raposa Exploradora', 'Caiu no mundo Pixel a explorar', 550, 'AVATAR', 'images/avatars/avatar_raposa_full_pixel_art.png', 'Incomum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('O Herói Retro', 'Nasceu para ser épico', 600, 'AVATAR', 'images/avatars/avatar_heroi_retro.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('A Heroína Retro', 'A rainha dos jogos antigos', 600, 'AVATAR', 'images/avatars/avatar_heroina_retro.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('O Vampiro Eterno', 'Imortal, elegante e letal', 650, 'AVATAR', 'images/avatars/avatar_vampiro.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('O Zumbi Insaciável', 'Devora respostas, não cérebros', 650, 'AVATAR', 'images/avatars/avatar_zumbi.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Caçador do Paranormal', 'O impossível é a sua especialidade', 700, 'AVATAR', 'images/avatars/avatar_detetive_sobrenatural.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('O Ninja das Sombras', 'Invisível. Rápido. Certeiro.', 700, 'AVATAR', 'images/avatars/avatar_ninja_sombrio_refinado.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Raposa Shinobi', 'A astúcia como única arma', 700, 'AVATAR', 'images/avatars/avatar_rapousa_ninja.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('A Génio Numérica', 'Vê equações onde os outros veem caos', 750, 'AVATAR', 'images/avatars/avatar_genia_matematica.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('O Vigilante Encapuzado', 'Protege o quiz das respostas erradas', 800, 'AVATAR', 'images/avatars/avatar_super_heroi_encapuzado.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('A Musa do Pop', 'Estrela do palco e da loja', 850, 'AVATAR', 'images/avatars/avatar_musa_do_pop.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Urso do Conhecimento', 'Grande, poderoso e sábio', 80, 'AVATAR', 'images/avatars/avatar_urso_fixe.png', 'Raro', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('A Coruja Omnisciente', 'Vê na escuridão, sabe tudo', 80, 'AVATAR', 'images/avatars/avatar_coruja_sabia.png', 'Raro', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('IA Dominante', 'A máquina que aprendeu tudo', 100, 'AVATAR', 'images/avatars/avatar_ia_dominante.png', 'Raro', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Senhor das Águas', 'O oceano obedece à sua vontade', 1000, 'AVATAR', 'images/avatars/avatar_aura_agua.png', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Mestre do Vento', 'Livre como o ar, ágil como o pensamento', 1000, 'AVATAR', 'images/avatars/avatar_aura_ar.png', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Filho das Chamas', 'Ardente, imparável, lendário', 1000, 'AVATAR', 'images/avatars/avatar_aura_fogo.png', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Guardião da Terra', 'A força da natureza em pessoa', 1000, 'AVATAR', 'images/avatars/avatar_aura_terra.png', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('O Homem da Aura', 'A energia dele é contagiante', 1200, 'AVATAR', 'images/avatars/avatar_homem_aura.png', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('O Cérebro Iluminado', 'A mente mais brilhante da loja', 1200, 'AVATAR', 'images/avatars/avatar_cerebro_brilhante.png', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Raposa da Sorte', 'A própria fortuna escolheu-te', 1250, 'AVATAR', 'images/avatars/avatar_raposa_transicao_sorte.png', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Ser de Partículas', 'Feito de energia pura do cosmos', 120, 'AVATAR', 'images/avatars/avatar_aura_particulas.png', 'Épico', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('O Invisível Cósmico', 'Além do visível, além da percepção', 120, 'AVATAR', 'images/avatars/avatar_invisivel_aura.png', 'Épico', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('IA Consciente', 'Processamento a 100%. Erro não encontrado.', 100, 'AVATAR', 'images/avatars/avatar_ia.png', 'Incomum', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('I''m Genius', 'QI acima de qualquer medição', 1500, 'AVATAR', 'images/avatars/avatar_im_genius.png', 'Lendário', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('I''m King', 'O trono pertence a quem sabe', 1500, 'AVATAR', 'images/avatars/avatar_im_king.png', 'Lendário', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('I''m Legend', 'Uma lenda não se apaga', 150, 'AVATAR', 'images/avatars/avatar_im_legend.png', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('I''m Rich', 'Rico em conhecimento e cristais', 150, 'AVATAR', 'images/avatars/avatar_im_rich.png', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('I''m Sorry', 'Humildade épica. Classe rara.', 150, 'AVATAR', 'images/avatars/avatar_im_sorry.png', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('No One Beats Me', 'Imbatível. Palavra final.', 180, 'AVATAR', 'images/avatars/avatar_no_one_beats_me.png', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Try Me', 'Desafia-me. Tens coragem?', 180, 'AVATAR', 'images/avatars/avatar_try_me.png', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Guardiã do Multiverso', 'Protege todas as realidades', 250, 'AVATAR', 'images/avatars/avatar_guardiao_do_multiverso.png', 'Supremo', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Guardião do Tempo', 'O relógio do universo', 250, 'AVATAR', 'images/avatars/avatar_guardiao_do_tempo.png', 'Supremo', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Mestre do Quiz', 'O criador. O único. O lendário.', 250, 'AVATAR', 'images/avatars/avatar_mestre_do_quiz.png', 'Supremo', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Moldura de Fogo', 'Chamas ardentes ao redor do seu avatar', 800, 'PROFILE_FRAME', 'images/frames/moldura_fogo_v2.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Moldura de Gelo', 'Aura congelante e impenetrável', 800, 'PROFILE_FRAME', 'images/frames/moldura_gelo_v2.png', 'Raro', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Moldura de Terra', 'Força e estabilidade da natureza', 1000, 'PROFILE_FRAME', 'images/frames/moldura_terra_v2.png', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Moldura de Ar', 'Ventos rápidos e cortantes', 1000, 'PROFILE_FRAME', 'images/frames/moldura_ar_v2.png', 'Épico', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Moldura de Energia', 'Pura energia cósmica pulsante', 80, 'PROFILE_FRAME', 'images/frames/moldura_energia_v2.png', 'Lendário', 'CRYSTALS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Recarga de Energia', 'Restaura a energia para 100', 150, 'ENERGY_REFILL', 'energy_refill', 'Comum', 'COINS');
INSERT INTO store_items (name, description, price, type, value, rarity, currency_type) VALUES ('Boost de XP (1h)', 'Dobra o XP ganho por 1 hora', 40, 'XP_BOOST', 'xp_boost_1h', 'Incomum', 'CRYSTALS');

-- Titles
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Iniciante', 'Jogue a sua primeira partida', 'GAMES_PLAYED', 1);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Curioso', 'Jogue 10 partidas', 'GAMES_PLAYED', 10);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Aprendiz', 'Jogue 25 partidas', 'GAMES_PLAYED', 25);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Entusiasta', 'Jogue 50 partidas', 'GAMES_PLAYED', 50);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Veterano', 'Jogue 100 partidas', 'GAMES_PLAYED', 100);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Resiliente', 'Jogue 250 partidas', 'GAMES_PLAYED', 250);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Viciado', 'Jogue 500 partidas', 'GAMES_PLAYED', 500);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Incansável', 'Jogue 1000 partidas', 'GAMES_PLAYED', 1000);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Lenda Viva', 'Jogue 2500 partidas', 'GAMES_PLAYED', 2500);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Mito do Quiz', 'Jogue 5000 partidas', 'GAMES_PLAYED', 5000);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Deus do Conhecimento', 'Jogue 10000 partidas', 'GAMES_PLAYED', 10000);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Primeira Vitória', 'Vença 1 partida', 'WINS', 1);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Vencedor', 'Vença 5 partidas', 'WINS', 5);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Campeão', 'Vença 15 partidas', 'WINS', 15);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Competitivo', 'Vença 30 partidas', 'WINS', 30);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Rei da Trívia', 'Vença 50 partidas', 'WINS', 50);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Mestre Estrategista', 'Vença 100 partidas', 'WINS', 100);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Imparável', 'Vença 250 partidas', 'WINS', 250);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Lenda Invicta', 'Vença 500 partidas', 'WINS', 500);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Titã', 'Vença 1000 partidas', 'WINS', 1000);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Soberano', 'Vença 2500 partidas', 'WINS', 2500);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Imperador', 'Vença 5000 partidas', 'WINS', 5000);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Nível 5', 'Alcance o nível 5', 'LEVEL', 5);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Mestre de Nível 10', 'Alcance o nível 10', 'LEVEL', 10);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Especialista', 'Alcance o nível 15', 'LEVEL', 15);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Intelectual', 'Alcance o nível 20', 'LEVEL', 20);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Sábio', 'Alcance o nível 30', 'LEVEL', 30);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Gênio', 'Alcance o nível 40', 'LEVEL', 40);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Mestre do Quiz', 'Alcance o nível 50', 'LEVEL', 50);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Professor', 'Alcance o nível 60', 'LEVEL', 60);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Pesquisador', 'Alcance o nível 70', 'LEVEL', 70);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Cientista', 'Alcance o nível 80', 'LEVEL', 80);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Polímata', 'Alcance o nível 90', 'LEVEL', 90);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Onisciente', 'Alcance o nível 100', 'LEVEL', 100);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Amigável', 'Convide 1 amigo', 'INVITES', 1);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Socializador', 'Convide 5 amigos', 'INVITES', 5);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Influenciador', 'Convide 10 amigos', 'INVITES', 10);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Embaixador', 'Convide 25 amigos', 'INVITES', 25);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Pop Star', 'Convide 50 amigos', 'INVITES', 50);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Ícone', 'Convide 100 amigos', 'INVITES', 100);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Apoiador', 'Adquira o status VIP', 'VIP', 1);
INSERT INTO titles (name, description, condition_type, condition_value) VALUES ('Membro VIP', 'Seja um Membro VIP Especial', 'VIP', 2);
